### ISSUE TITLE
Handle spaces in code

### ISSUE THREAD

**Issue by meichthys** [metikular/coupon-store#18]
Currently if a space is added to a code that is set as a barcode it results in an error. This makes it impossible to view or remove the code since it is saved, but each time i try to open the code, the error is displayed.
```
We're sorry, but something went wrong. 
If you are the application owner check the logs for more information.
```

Server logs show:
```
I, [2022-09-30T13:34:43.546708 #1]  INFO -- : [c6148abb-59d9-4a0c-a09b-01d8d152cca6] Processing by CouponsController#update as HTML

I, [2022-09-30T13:34:43.546750 #1]  INFO -- : [c6148abb-59d9-4a0c-a09b-01d8d152cca6]   Parameters: {"authenticity_token"=>"[FILTERED]", "coupon"=>{"code"=>"FFG ", "barcode_type"=>"ean_13", "store"=>"", "description"=>"", "valid_until"=>""}, "commit"=>"Update", "locale"=>"en", "id"=>"2"}

I, [2022-09-30T13:34:43.553338 #1]  INFO -- : [c6148abb-59d9-4a0c-a09b-01d8d152cca6] Redirected to https://couponstore.mydomain.com/en/coupons/2

I, [2022-09-30T13:34:43.553493 #1]  INFO -- : [c6148abb-59d9-4a0c-a09b-01d8d152cca6] Completed 302 Found in 7ms (ActiveRecord: 2.9ms | Allocations: 1999)

I, [2022-09-30T13:34:43.682457 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359] Started GET "/en/coupons/2" for 74.67.79.83 at 2022-09-30 13:34:43 +0000

I, [2022-09-30T13:34:43.682979 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359] Processing by CouponsController#show as HTML

I, [2022-09-30T13:34:43.683020 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359]   Parameters: {"locale"=>"en", "id"=>"2"}

I, [2022-09-30T13:34:43.687171 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359]   Rendered coupons/show.html.haml within layouts/application (Duration: 1.2ms | Allocations: 547)

I, [2022-09-30T13:34:43.687249 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359]   Rendered layout layouts/application.html.haml (Duration: 1.3ms | Allocations: 590)

I, [2022-09-30T13:34:43.687421 #1]  INFO -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359] Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.3ms | Allocations: 1829)

F, [2022-09-30T13:34:43.688581 #1] FATAL -- : [8516e9ef-fb56-46f5-9e81-6e795bd86359]   

[8516e9ef-fb56-46f5-9e81-6e795bd86359] ActionView::Template::Error (data not valid):

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     15:     = link_to coupons_path do

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     16:       = heroicon :x, options: {class: 'w-6 h-6'}

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     17: 

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     18: .barcode.mt-10.flex.justify-center= barcode_svg(@coupon.code, @coupon.barcode_type)

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     19: 

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     20: - content_for :footer do

[8516e9ef-fb56-46f5-9e81-6e795bd86359]     21:   .flex.flex-col

[8516e9ef-fb56-46f5-9e81-6e795bd86359]   

[8516e9ef-fb56-46f5-9e81-6e795bd86359] app/helpers/barcode_helper.rb:12:in `new'

[8516e9ef-fb56-46f5-9e81-6e795bd86359] app/helpers/barcode_helper.rb:12:in `barcode_svg'

[8516e9ef-fb56-46f5-9e81-6e795bd86359] app/views/coupons/show.html.haml:18

[8516e9ef-fb56-46f5-9e81-6e795bd86359] app/controllers/application_controller.rb:10:in `switch_locale'
```

**Comment by phylor** [comment]
Thank you for the report!

This has been fixed in 329565837b8d56ed30541d413cb286a098d85d44 and is being released as v1.1.0-rc2 (image is building).

That is, the app won't crash anymore. The barcode is not shown though. I'll fix that later.

**Comment by phylor** [comment]
Fixed in 554294f9aa8a209e9858aaa7ef9eadee6d66bd31
